# Generated by Django 2.2.3 on 2019-11-26 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.utilities


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191126_1222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ('super_category__order', 'super_category__name', 'order', 'name'), 'verbose_name': 'SubCategory', 'verbose_name_plural': 'SubCategories'},
        ),
        migrations.AlterModelOptions(
            name='supercategory',
            options={'ordering': ('order', 'name'), 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.CreateModel(
            name='Bb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Movie')),
                ('content', models.TextField(verbose_name='Content')),
                ('contacts', models.TextField(verbose_name='Contacts')),
                ('image', models.ImageField(blank=True, upload_to=main.utilities.get_timestamp_path, verbose_name='Image')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Add to lisat?')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Publshed')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author of movie')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.SubCategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movie',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdditinalImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=main.utilities.get_timestamp_path, verbose_name='Image')),
                ('bb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Bb', verbose_name='Movie')),
            ],
            options={
                'verbose_name': 'additional illustration',
                'verbose_name_plural': 'additional illustrations',
            },
        ),
    ]
