# Generated by Django 2.2.3 on 2019-11-30 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_subcategory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdditinalImage',
            new_name='AdditionalImage',
        ),
        migrations.AlterField(
            model_name='bb',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.SubCategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Published'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Add to list?'),
        ),
    ]
