# Generated by Django 2.2.3 on 2019-12-02 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20191130_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30, verbose_name='Author')),
                ('content', models.TextField(verbose_name='Content')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Display on screen?')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Published')),
                ('bb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Bb', verbose_name='Movie')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['created_at'],
            },
        ),
    ]
